---
- hosts: all
  become: yes
  remote_user: ubuntu
  tasks:

  - name: Instalando unzip
    apt:
      name: unzip
      state: latest
      update_cache: yes

  - name: criar usuario consul, grupo consul
    user:
      name: consul
      state: present
      shell: /bin/false
      system: yes
      createhome: no
      home: /etc/consul.d

  - name: criar diretorio /var/lib/consul.d
    ansible.builtin.file:
      path: /var/lib/consul.d
      state: directory
      mode: '0755'

  - name: aplicar permissao /var/lib/consul.d
    ansible.builtin.file:
      path: /var/lib/consul.d
      state: directory
      recurse: yes
      owner: consul
      group: consul

  - name: criar diretorio /etc/consul.d
    ansible.builtin.file:
      path: /etc/consul.d
      state: directory
      mode: '0755'

  - name: instalar consul
    unarchive:
     src: https://releases.hashicorp.com/consul/1.9.3/consul_1.9.3_linux_amd64.zip
     dest: /usr/bin
     remote_src: True

  - name: Copiando consul.service
    copy:
      src: configs/consul_master.service
      dest: /usr/lib/systemd/system/consul.service

  - name: Copiando consul.hlc
    copy:
      src: configs/consul_master.hlc
      dest: /etc/consul.d/consul.hcl

  - name: Instalando o nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: Copiando index.html personalizado
    copy:
      src: configs/index.html.j2
      dest: /var/www/html/index.html

  - name: Copiando nginx default site
    copy:
      src: configs/nginx_default_master.conf
      dest: /etc/nginx/sites-enabled/default

  - name: desativando nginx (sera ativado via terraform)
    service:
      name: nginx
      state: stopped
      enabled: no

  - name: desativando o consul (sera ativado via terraform)
    service:
      name: consul
      state: stopped
      enabled: no

