---
- hosts: all
  become: yes
  remote_user: ubuntu
  tasks:

  - name: Instalando unzip
    apt:
      name: unzip
      state: latest
      update_cache: yes

  - name: criar usuario consul, grupo consul
    user:
      name: consul
      state: present
      shell: /bin/false
      system: yes
      createhome: no
      home: /etc/consul.d

  - name: criar diretorio /etc/consul.d
    ansible.builtin.file:
      path: /etc/consul.d
      state: directory
      mode: '0755'

  - name: criar diretorio /var/lib/consul.d
    ansible.builtin.file:
      path: /var/lib/consul.d
      state: directory
      mode: '0755'

  - name: mudar permissão /var/lib/consul.d
    ansible.builtin.file:
      path: /var/lib/consul.d
      state: directory
      recurse: yes
      owner: consul
      group: consul

  - name: instalar consul
    unarchive:
      src: https://releases.hashicorp.com/consul/1.9.3/consul_1.9.3_linux_amd64.zip
      dest: /usr/bin
      remote_src: True

  - name: Copiando consul.service
    copy:
      src: configs/consul_slave.service
      dest: /usr/lib/systemd/system/consul.service

  - name: Copiando consul.hlc (template)
    copy:
      src: configs/consul_slave.hcl.j2
      dest: /etc/consul.d/consul.hcl

  - name: Copiando consul webserver json
    copy:
      src: configs/consul_monitor_slave.json
      dest: /etc/consul.d/monitor.json

  - name: Deixar serviço parado (iniciar via terraform no provisionamento)
    service:
      name: consul
      state: stopped
      enabled: no

# Grafana
  - name: Install nessesary package
    apt: 
        name: apt-transport-https
        state: present
        update_cache: yes

  - name: add grafana gpg key
    shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

  - name: add grafana repo 
    apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      state: present
      filename: grafana

  - name: Install grafana
    apt: 
      name: grafana
      state: present
      update_cache: yes

  - name: grafana service
    service:
      name: grafana-server
      enabled: no
      state: stopped

  - name: instalar Prometheus
    unarchive:
      src: https://github.com/prometheus/prometheus/releases/download/v2.25.0/prometheus-2.25.0.linux-amd64.tar.gz
      dest: /tmp
      remote_src: True

  - name: mover Prometheus
    command: mv /tmp/prometheus-2.25.0.linux-amd64 /etc/prometheus

  - name: mover comando1
    command: mv /etc/prometheus/prometheus /usr/local/bin/

  - name: mover comando1
    command: mv /etc/prometheus/promtool /usr/local/bin/

  - name: criar usuario prometheus, grupo prometheus
    user:
      name: prometheus
      state: present
      shell: /bin/false
      system: yes
      createhome: no
      home: /etc/prometheus

  - name: criar diretorio /var/lib/prometheus
    ansible.builtin.file:
      path: /var/lib/prometheus
      state: directory
      mode: '0755'

  - name: Copiando prometheus.yml
    copy:
      src: configs/prometheus.yml
      dest: /etc/prometheus/prometheus.yml

  - name: Copiando prometheus.service
    copy:
      src: configs/prometheus.service
      dest: /etc/systemd/system/prometheus.service

  - name: aplicar permissao /var/lib/prometheus
    ansible.builtin.file:
      path: /var/lib/prometheus
      state: directory
      recurse: yes
      owner: prometheus
      group: prometheus

  - name: aplicar permissao /etc/prometheus
    ansible.builtin.file:
      path: /etc/prometheus
      state: directory
      recurse: yes
      owner: prometheus
      group: prometheus

  - name: aplicar permissao /usr/local/bin/prometheus
    ansible.builtin.file:
      path: /usr/local/bin/prometheus
      state: file
      owner: prometheus
      group: prometheus

  - name: aplicar permissao /usr/local/bin/promtool
    ansible.builtin.file:
      path: /usr/local/bin/promtool
      state: file
      owner: prometheus
      group: prometheus

  - name: Prometheus service
    service:
      name: prometheus
      enabled: no
      state: stopped

